deploy:
  provider: script
  skip_cleanup: true
  script: deploy.sh
  on:
    tags: true
    branch: master
env:
  global:
  - secure: VbttZdMAJiULKqNcTqygZ+Jd2PVwQMtRDnLfPB9SYYAoPnoFVXQox1APX6E8twp7UGkxl+8SwIk3JjiEmcYB3tlVvZBy+vJJ07yOHbJFen2FzvW31nbfZYYLPH2GBvX9F0kNXBopBq1nPPxbut7HrncYcoU9xrbpClgE0Lf+wNRyfJacjId6hddYzOTEPjQQf2Z4Hp4xVTToqOpSonE79yeStNowTbJygt0lIODupyFoyoUdUfVAlciPT1ubpD1l4VgjRTpugeRTs3tvZQYGohVBAurQKc0H0nkneietFxKYddXObVbmgur9tfs1u5dm6N6V+c0/hb58K1RU3idaZZmBoTtMYv+si0PinhTEIw38Kvx0JHJvygU7RF6mf+OaLcG55fGwgZX1aLo8vhDO2nsFnid8468QvPgfFVKJTxU5IyGn8jAzhzN9OJcgG1NDS0uk3S9HA569NBe68oeVoNqPPBLJ3nYfxOL2Pcg+6aIwn3Uzx6YgKQsE9Pt1GcHhs4AMokbFURpEF2zWUP/XdoRPj2CtYR3dirSUCH21O/n/EitKw0qr8SKLhVlUodA2xCikCycOM7cEkA6Eg4gao7t1ChZh5gbb+Ia8JYmwhEplslxvUo513/ffVb9noS0+NkaoqieV9Wu6vaUoTEd+iKixAo15d9uBbogNwVFSySk=
  - secure: h0N1iItcwRLBHfZaDArKMjm9EKHcJZQijDOs5lugjbFfOeVk3HPNDhl17/+uLRGYJyirJLGQUG+EKwEPyvHa/LkW7m3qpQLt2D5ej5u4Kcdn6bSrO17Sj+GQ8Trd83C101+ne0/dUH4QnAX4qjWaZoTBA+Ayy3hziJKbFVQwcJ9d/1KOQ6h4wIX+4XL2GJVwyLYRsZb0Zxkky26qekWmduTuTEEXBRPuppB5SCnqWtEz4WpLvmx+PJoK/ju2MmDAMFJ9K92w7YlQWu3mECqlsJjAJ7DvjCSQEdCuQw0dClxPjQ6XGD6bxhs7kIFgy5a0WinNkHwhAE40VeZ9koyoC6/SZ3k/sy52MhJnDYUf7TGCJTDc31zm+ybZ7qGNPNQP6YIzUCODDsUK9heLh2PPJ6bJowpHJMCWwN7F3MaXtvxhAeK2T7tdoYddzew1fi7bt46ZBuyoBRTD+NiywoRSFJSMTdHlQDqfK4bsAt7ypJ5wiKPADMEuN38gNtecK1Sn7pQ0e+0vki4wGl0M3BAiV5cR5G607/6D+TKBa8jvwvgndL4WLI5gu2aNSdVIgPZq4ds9cKnBkSAydZolg8Lr7nPNu+QoUHxu2vl6T1eWuBZs9EpVwBGOidvWv8GcONC+7ITT2mihAmainfoH5hqVcPdu9sP0wow+IQR0m8JwPYk=
language: node_js
node_js:
- "stable"
